### ISSUE TITLE
start Crash

### ISSUE THREAD

**Issue by B4unty** [kopierschnitte/venus.dbus-senec-enfluri#3]
python /data/dbus-iobroker-smartmeter/dbus-iobroker-smartmeter.py 
2022-11-06 11:29:43,469 root INFO Start
2022-11-06 11:29:43,494 root INFO registered ourselves on D-Bus as com.victronenergy.grid.http_40
2022-11-06 11:29:43,574 root CRITICAL Error at main
Traceback (most recent call last):
  File "/data/dbus-iobroker-smartmeter/dbus-iobroker-smartmeter.py", line 277, in main
    pvac_output = DbusIobrokerSmartmeterService(
  File "/data/dbus-iobroker-smartmeter/dbus-iobroker-smartmeter.py", line 38, in __init__
    self.grid_bought_start = next((x for x in meter_data if x['id'] ==
TypeError: 'NoneType' object is not subscriptable

**Comment by kopierschnitte** [comment]
This is related to the iobroker fork...

**Comment by B4unty** [comment]
> This is related to the iobroker fork...

Can I solve the problem?

**Comment by ErazorVIP** [comment]
@B4unty Did u fixed it?
